'use strict';
const { test } = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');
const { render, parseRules, extractFix, MAX_BYTES } = require('../scripts/sync-plugin-guidance');

const repoRoot = path.join(__dirname, '..', '..');
const master = fs.readFileSync(path.join(repoRoot, 'claude-security-guidance.md'), 'utf8').replace(/\r\n/g, '\n');

test('digest render is deterministic', () => {
  assert.equal(render(), render());
});

test('digest is under the 8192-byte Anthropic cap', () => {
  assert.ok(Buffer.byteLength(render(), 'utf8') <= MAX_BYTES, 'plugin-guidance.md exceeds the 8 KB cap');
});

test('digest fits the cap and accounts for every rule (inline cue or overflow pointer)', () => {
  // Scale-invariant: SSS can grow to thousands of rules but the plugin file is
  // hard-capped at 8192 B by the consumer. Every rule must be EITHER an inline cue
  // OR counted in the single overflow pointer — never silently dropped.
  const out = render();
  const rules = parseRules(master);
  assert.ok(rules.length >= 52, 'expected the master to parse to >=52 rules');
  assert.ok(Buffer.byteLength(out, 'utf8') <= MAX_BYTES, 'digest exceeds the 8 KB cap');
  const cueIds = (out.match(/^- \*\*(SOL-\d{3})\*\* · /gm) || []).map((s) => s.match(/SOL-\d{3}/)[0]);
  assert.equal(new Set(cueIds).size, cueIds.length, 'duplicate cue line in the digest');
  for (const id of cueIds) assert.ok(rules.some((r) => r.id === id), `${id} cue is not a real rule`);
  const omitted = rules.length - cueIds.length;
  if (omitted > 0) {
    const m = out.match(/\+ (\d+) more rules/);
    assert.ok(m, 'rules omitted from the digest but no overflow pointer line');
    assert.equal(Number(m[1]), omitted, 'overflow count != omitted-rule count');
  } else {
    assert.ok(!/\+ \d+ more rules/.test(out), 'overflow pointer present but nothing was omitted');
  }
});

test('when budgeted, no high-tier rule is dropped while a low-tier rule stays inline', () => {
  const out = render();
  const meta = JSON.parse(fs.readFileSync(path.join(repoRoot, 'rules-meta.json'), 'utf8')).rules;
  const inline = new Set((out.match(/^- \*\*(SOL-\d{3})\*\*/gm) || []).map((s) => s.match(/SOL-\d{3}/)[0]));
  const rules = parseRules(master);
  const highOmitted = rules.some((r) => !inline.has(r.id) && (meta[r.id] || {}).tier === 'high');
  const lowInline = rules.some((r) => inline.has(r.id) && (meta[r.id] || {}).tier !== 'high');
  if (highOmitted) assert.ok(!lowInline, 'a high-tier rule was dropped while a low-tier rule stayed inline');
});

test('every high-tier rule stays inline — loud tripwire on digest budget pressure', () => {
  // The scale-invariant packer preserves the no-high-dropped-while-low-kept invariant even
  // under capacity pressure, but a high-tier rule silently sliding into the overflow is
  // still a regression for a security cheat-sheet. Assert none overflow; if one does, the
  // fix is to lower RESERVE or tighten a high-tier Fix cue — not to accept the eviction.
  const out = render();
  const meta = JSON.parse(fs.readFileSync(path.join(repoRoot, 'rules-meta.json'), 'utf8')).rules;
  const inline = new Set((out.match(/^- \*\*(SOL-\d{3})\*\*/gm) || []).map((s) => s.match(/SOL-\d{3}/)[0]));
  const highOverflowed = parseRules(master)
    .filter((r) => (meta[r.id] || {}).tier === 'high' && !inline.has(r.id))
    .map((r) => r.id);
  assert.deepStrictEqual(highOverflowed, [], `high-tier rule(s) overflowed the digest: ${highOverflowed.join(', ')} — lower RESERVE or tighten a high-tier Fix cue so every high-tier cue fits inline`);
});

test('every rule body yields a non-empty single-line fix cue', () => {
  for (const r of parseRules(master)) {
    const fix = extractFix(r.body);
    assert.ok(fix.length > 0, `${r.id}: empty fix cue`);
    assert.ok(!fix.includes('\n') && !fix.includes('|'), `${r.id}: fix cue has a newline/pipe`);
    assert.ok(!/\*\([^)]*\)\*$/.test(fix), `${r.id}: trailing *(provenance)* leaked into the cue`);
  }
});

test('extractFix strips the trailing *(...)* note before finding "Fix:" (anti-corruption)', () => {
  // a future rule whose provenance note itself contains "Fix:" must not corrupt the cue
  assert.equal(extractFix('Bug here. Fix: `require_keys_neq!`. *(superseded the old Fix: hack)*'), '`require_keys_neq!`');
  assert.equal(extractFix('Bug. Fix: do the right thing. *(2 wins)*'), 'do the right thing');
  assert.throws(() => extractFix('A body with no remedy clause at all.'), /no "Fix:" clause/);
});

test('digest keeps the threat model + checklist + a full-detail pointer', () => {
  const out = render();
  assert.match(out, /## Threat model/);
  assert.match(out, /## Review checklist/);
  assert.match(out, /list_solana_security_rules/); // points at the MCP tool for full detail
  assert.match(out, /claude-security-guidance\.md/); // and at the full master
  assert.match(out, /GENERATED by/); // self-declares generated
});

test('committed plugin-guidance.md is in sync with the generator', () => {
  const committed = fs.readFileSync(path.join(repoRoot, 'plugin-guidance.md'), 'utf8').replace(/\r\n/g, '\n');
  assert.equal(committed, render(), 'plugin-guidance.md is stale — run npm run sync:plugin-guidance');
});
